/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Route = IDL.Record({
  'id' : IDL.Text,
  'fromDistrict' : IDL.Text,
  'name' : IDL.Text,
  'segments' : IDL.Vec(IDL.Text),
  'reasoning' : IDL.Text,
  'totalDistance' : IDL.Float64,
  'alternateOf' : IDL.Opt(IDL.Text),
  'isOptimal' : IDL.Bool,
  'toDistrict' : IDL.Text,
  'estimatedMinutes' : IDL.Nat,
});
export const AnomalyType = IDL.Variant({
  'EmergencyVehicle' : IDL.Null,
  'Pedestrian' : IDL.Null,
  'Obstacle' : IDL.Null,
  'Animal' : IDL.Null,
  'Accident' : IDL.Null,
  'VehicleBreakdown' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const Anomaly = IDL.Record({
  'id' : IDL.Text,
  'segmentId' : IDL.Text,
  'anomalyType' : AnomalyType,
  'detectedAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'reasoning' : IDL.Text,
  'severity' : AlertSeverity,
});
export const EmergencyAlert = IDL.Record({
  'id' : IDL.Text,
  'vehicleType' : IDL.Text,
  'segmentId' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'triggeredAt' : IDL.Int,
  'recommendedAction' : IDL.Text,
  'priority' : IDL.Nat,
});
export const IncidentStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Validated' : IDL.Null,
  'Resolved' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Incident = IDL.Record({
  'id' : IDL.Text,
  'status' : IncidentStatus,
  'segmentId' : IDL.Text,
  'validationScore' : IDL.Nat,
  'reporterNote' : IDL.Text,
  'reportedAt' : IDL.Int,
  'validatedAt' : IDL.Opt(IDL.Int),
  'incidentType' : IDL.Text,
});
export const TrafficLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'NoTraffic' : IDL.Null,
});
export const TrafficSegment = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'avgSpeed' : IDL.Float64,
  'waitTimeSeconds' : IDL.Nat,
  'congestionPct' : IDL.Nat,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'trafficLevel' : TrafficLevel,
  'vehicleCount' : IDL.Nat,
});
export const SystemStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Operational' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Degraded' : IDL.Null,
});
export const SystemComponent = IDL.Record({
  'id' : IDL.Text,
  'status' : SystemStatus,
  'uptimePct' : IDL.Float64,
  'name' : IDL.Text,
  'lastChecked' : IDL.Int,
  'failureCount' : IDL.Nat,
  'componentType' : IDL.Text,
});
export const WeatherCondition = IDL.Variant({
  'Fog' : IDL.Null,
  'Storm' : IDL.Null,
  'Rain' : IDL.Null,
  'Snow' : IDL.Null,
  'Clear' : IDL.Null,
});
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'affectedDistricts' : IDL.Vec(IDL.Text),
  'windSpeed' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'recommendation' : IDL.Text,
  'visibility' : IDL.Nat,
  'condition' : WeatherCondition,
});
export const TrafficSnapshot = IDL.Record({
  'activeEmergencies' : IDL.Vec(EmergencyAlert),
  'segments' : IDL.Vec(TrafficSegment),
  'activeAnomalies' : IDL.Vec(Anomaly),
  'timestamp' : IDL.Int,
  'weather' : WeatherData,
  'systemHealth' : IDL.Nat,
});

export const idlService = IDL.Service({
  'acknowledgeEmergency' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'computeOptimalRoute' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Route)],
      ['query'],
    ),
  'getAnomalies' : IDL.Func([IDL.Bool], [IDL.Vec(Anomaly)], ['query']),
  'getEmergencyAlerts' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(EmergencyAlert)],
      ['query'],
    ),
  'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getSegments' : IDL.Func([], [IDL.Vec(TrafficSegment)], ['query']),
  'getSystemComponents' : IDL.Func([], [IDL.Vec(SystemComponent)], ['query']),
  'getTrafficSnapshot' : IDL.Func([], [TrafficSnapshot], ['query']),
  'getWaitTimeEstimate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getWeather' : IDL.Func([], [WeatherData], ['query']),
  'reportIncident' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Incident], []),
  'resetSimulation' : IDL.Func([], [], []),
  'resolveAnomaly' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'simulateTick' : IDL.Func([], [], []),
  'triggerEmergencySimulation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [EmergencyAlert],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Route = IDL.Record({
    'id' : IDL.Text,
    'fromDistrict' : IDL.Text,
    'name' : IDL.Text,
    'segments' : IDL.Vec(IDL.Text),
    'reasoning' : IDL.Text,
    'totalDistance' : IDL.Float64,
    'alternateOf' : IDL.Opt(IDL.Text),
    'isOptimal' : IDL.Bool,
    'toDistrict' : IDL.Text,
    'estimatedMinutes' : IDL.Nat,
  });
  const AnomalyType = IDL.Variant({
    'EmergencyVehicle' : IDL.Null,
    'Pedestrian' : IDL.Null,
    'Obstacle' : IDL.Null,
    'Animal' : IDL.Null,
    'Accident' : IDL.Null,
    'VehicleBreakdown' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const Anomaly = IDL.Record({
    'id' : IDL.Text,
    'segmentId' : IDL.Text,
    'anomalyType' : AnomalyType,
    'detectedAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'reasoning' : IDL.Text,
    'severity' : AlertSeverity,
  });
  const EmergencyAlert = IDL.Record({
    'id' : IDL.Text,
    'vehicleType' : IDL.Text,
    'segmentId' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'triggeredAt' : IDL.Int,
    'recommendedAction' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const IncidentStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Validated' : IDL.Null,
    'Resolved' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Incident = IDL.Record({
    'id' : IDL.Text,
    'status' : IncidentStatus,
    'segmentId' : IDL.Text,
    'validationScore' : IDL.Nat,
    'reporterNote' : IDL.Text,
    'reportedAt' : IDL.Int,
    'validatedAt' : IDL.Opt(IDL.Int),
    'incidentType' : IDL.Text,
  });
  const TrafficLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'NoTraffic' : IDL.Null,
  });
  const TrafficSegment = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'avgSpeed' : IDL.Float64,
    'waitTimeSeconds' : IDL.Nat,
    'congestionPct' : IDL.Nat,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'trafficLevel' : TrafficLevel,
    'vehicleCount' : IDL.Nat,
  });
  const SystemStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Operational' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Degraded' : IDL.Null,
  });
  const SystemComponent = IDL.Record({
    'id' : IDL.Text,
    'status' : SystemStatus,
    'uptimePct' : IDL.Float64,
    'name' : IDL.Text,
    'lastChecked' : IDL.Int,
    'failureCount' : IDL.Nat,
    'componentType' : IDL.Text,
  });
  const WeatherCondition = IDL.Variant({
    'Fog' : IDL.Null,
    'Storm' : IDL.Null,
    'Rain' : IDL.Null,
    'Snow' : IDL.Null,
    'Clear' : IDL.Null,
  });
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'affectedDistricts' : IDL.Vec(IDL.Text),
    'windSpeed' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'recommendation' : IDL.Text,
    'visibility' : IDL.Nat,
    'condition' : WeatherCondition,
  });
  const TrafficSnapshot = IDL.Record({
    'activeEmergencies' : IDL.Vec(EmergencyAlert),
    'segments' : IDL.Vec(TrafficSegment),
    'activeAnomalies' : IDL.Vec(Anomaly),
    'timestamp' : IDL.Int,
    'weather' : WeatherData,
    'systemHealth' : IDL.Nat,
  });
  
  return IDL.Service({
    'acknowledgeEmergency' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'computeOptimalRoute' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Route)],
        ['query'],
      ),
    'getAnomalies' : IDL.Func([IDL.Bool], [IDL.Vec(Anomaly)], ['query']),
    'getEmergencyAlerts' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(EmergencyAlert)],
        ['query'],
      ),
    'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getSegments' : IDL.Func([], [IDL.Vec(TrafficSegment)], ['query']),
    'getSystemComponents' : IDL.Func([], [IDL.Vec(SystemComponent)], ['query']),
    'getTrafficSnapshot' : IDL.Func([], [TrafficSnapshot], ['query']),
    'getWaitTimeEstimate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getWeather' : IDL.Func([], [WeatherData], ['query']),
    'reportIncident' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Incident], []),
    'resetSimulation' : IDL.Func([], [], []),
    'resolveAnomaly' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'simulateTick' : IDL.Func([], [], []),
    'triggerEmergencySimulation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [EmergencyAlert],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };