/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertSeverity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface Anomaly {
  'id' : string,
  'segmentId' : string,
  'anomalyType' : AnomalyType,
  'detectedAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'reasoning' : string,
  'severity' : AlertSeverity,
}
export type AnomalyType = { 'EmergencyVehicle' : null } |
  { 'Pedestrian' : null } |
  { 'Obstacle' : null } |
  { 'Animal' : null } |
  { 'Accident' : null } |
  { 'VehicleBreakdown' : null };
export interface EmergencyAlert {
  'id' : string,
  'vehicleType' : string,
  'segmentId' : string,
  'description' : string,
  'isActive' : boolean,
  'triggeredAt' : bigint,
  'recommendedAction' : string,
  'priority' : bigint,
}
export interface Incident {
  'id' : string,
  'status' : IncidentStatus,
  'segmentId' : string,
  'validationScore' : bigint,
  'reporterNote' : string,
  'reportedAt' : bigint,
  'validatedAt' : [] | [bigint],
  'incidentType' : string,
}
export type IncidentStatus = { 'Rejected' : null } |
  { 'Validated' : null } |
  { 'Resolved' : null } |
  { 'Pending' : null };
export interface Route {
  'id' : string,
  'fromDistrict' : string,
  'name' : string,
  'segments' : Array<string>,
  'reasoning' : string,
  'totalDistance' : number,
  'alternateOf' : [] | [string],
  'isOptimal' : boolean,
  'toDistrict' : string,
  'estimatedMinutes' : bigint,
}
export interface SystemComponent {
  'id' : string,
  'status' : SystemStatus,
  'uptimePct' : number,
  'name' : string,
  'lastChecked' : bigint,
  'failureCount' : bigint,
  'componentType' : string,
}
export type SystemStatus = { 'Failed' : null } |
  { 'Operational' : null } |
  { 'Maintenance' : null } |
  { 'Degraded' : null };
export type TrafficLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'NoTraffic' : null };
export interface TrafficSegment {
  'id' : string,
  'lat' : number,
  'lon' : number,
  'avgSpeed' : number,
  'waitTimeSeconds' : bigint,
  'congestionPct' : bigint,
  'name' : string,
  'district' : string,
  'trafficLevel' : TrafficLevel,
  'vehicleCount' : bigint,
}
export interface TrafficSnapshot {
  'activeEmergencies' : Array<EmergencyAlert>,
  'segments' : Array<TrafficSegment>,
  'activeAnomalies' : Array<Anomaly>,
  'timestamp' : bigint,
  'weather' : WeatherData,
  'systemHealth' : bigint,
}
export type WeatherCondition = { 'Fog' : null } |
  { 'Storm' : null } |
  { 'Rain' : null } |
  { 'Snow' : null } |
  { 'Clear' : null };
export interface WeatherData {
  'temperature' : number,
  'affectedDistricts' : Array<string>,
  'windSpeed' : number,
  'updatedAt' : bigint,
  'recommendation' : string,
  'visibility' : bigint,
  'condition' : WeatherCondition,
}
export interface _SERVICE {
  'acknowledgeEmergency' : ActorMethod<[string], boolean>,
  'computeOptimalRoute' : ActorMethod<[string, string], [] | [Route]>,
  'getAnomalies' : ActorMethod<[boolean], Array<Anomaly>>,
  'getEmergencyAlerts' : ActorMethod<[boolean], Array<EmergencyAlert>>,
  'getIncidents' : ActorMethod<[], Array<Incident>>,
  'getRoutes' : ActorMethod<[], Array<Route>>,
  'getSegments' : ActorMethod<[], Array<TrafficSegment>>,
  'getSystemComponents' : ActorMethod<[], Array<SystemComponent>>,
  'getTrafficSnapshot' : ActorMethod<[], TrafficSnapshot>,
  'getWaitTimeEstimate' : ActorMethod<[string], bigint>,
  'getWeather' : ActorMethod<[], WeatherData>,
  'reportIncident' : ActorMethod<[string, string, string], Incident>,
  'resetSimulation' : ActorMethod<[], undefined>,
  'resolveAnomaly' : ActorMethod<[string], boolean>,
  'simulateTick' : ActorMethod<[], undefined>,
  'triggerEmergencySimulation' : ActorMethod<[string, string], EmergencyAlert>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];