/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EmergencyAlert {
    id: string;
    vehicleType: string;
    segmentId: string;
    description: string;
    isActive: boolean;
    triggeredAt: bigint;
    recommendedAction: string;
    priority: bigint;
}
export interface Anomaly {
    id: string;
    segmentId: string;
    anomalyType: AnomalyType;
    detectedAt: bigint;
    description: string;
    isActive: boolean;
    reasoning: string;
    severity: AlertSeverity;
}
export interface TrafficSegment {
    id: string;
    lat: number;
    lon: number;
    avgSpeed: number;
    waitTimeSeconds: bigint;
    congestionPct: bigint;
    name: string;
    district: string;
    trafficLevel: TrafficLevel;
    vehicleCount: bigint;
}
export interface WeatherData {
    temperature: number;
    affectedDistricts: Array<string>;
    windSpeed: number;
    updatedAt: bigint;
    recommendation: string;
    visibility: bigint;
    condition: WeatherCondition;
}
export interface Incident {
    id: string;
    status: IncidentStatus;
    segmentId: string;
    validationScore: bigint;
    reporterNote: string;
    reportedAt: bigint;
    validatedAt?: bigint;
    incidentType: string;
}
export interface SystemComponent {
    id: string;
    status: SystemStatus;
    uptimePct: number;
    name: string;
    lastChecked: bigint;
    failureCount: bigint;
    componentType: string;
}
export interface TrafficSnapshot {
    activeEmergencies: Array<EmergencyAlert>;
    segments: Array<TrafficSegment>;
    activeAnomalies: Array<Anomaly>;
    timestamp: bigint;
    weather: WeatherData;
    systemHealth: bigint;
}
export interface Route {
    id: string;
    fromDistrict: string;
    name: string;
    segments: Array<string>;
    reasoning: string;
    totalDistance: number;
    alternateOf?: string;
    isOptimal: boolean;
    toDistrict: string;
    estimatedMinutes: bigint;
}
export enum AlertSeverity {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum AnomalyType {
    EmergencyVehicle = "EmergencyVehicle",
    Pedestrian = "Pedestrian",
    Obstacle = "Obstacle",
    Animal = "Animal",
    Accident = "Accident",
    VehicleBreakdown = "VehicleBreakdown"
}
export enum IncidentStatus {
    Rejected = "Rejected",
    Validated = "Validated",
    Resolved = "Resolved",
    Pending = "Pending"
}
export enum SystemStatus {
    Failed = "Failed",
    Operational = "Operational",
    Maintenance = "Maintenance",
    Degraded = "Degraded"
}
export enum TrafficLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    NoTraffic = "NoTraffic"
}
export enum WeatherCondition {
    Fog = "Fog",
    Storm = "Storm",
    Rain = "Rain",
    Snow = "Snow",
    Clear = "Clear"
}
export interface backendInterface {
    acknowledgeEmergency(alertId: string): Promise<boolean>;
    computeOptimalRoute(fromDistrict: string, toDistrict: string): Promise<Route | null>;
    getAnomalies(activeOnly: boolean): Promise<Array<Anomaly>>;
    getEmergencyAlerts(activeOnly: boolean): Promise<Array<EmergencyAlert>>;
    getIncidents(): Promise<Array<Incident>>;
    getRoutes(): Promise<Array<Route>>;
    getSegments(): Promise<Array<TrafficSegment>>;
    getSystemComponents(): Promise<Array<SystemComponent>>;
    getTrafficSnapshot(): Promise<TrafficSnapshot>;
    getWaitTimeEstimate(segmentId: string): Promise<bigint>;
    getWeather(): Promise<WeatherData>;
    reportIncident(segmentId: string, incidentType: string, reporterNote: string): Promise<Incident>;
    resetSimulation(): Promise<void>;
    resolveAnomaly(anomalyId: string): Promise<boolean>;
    simulateTick(): Promise<void>;
    triggerEmergencySimulation(segmentId: string, vehicleType: string): Promise<EmergencyAlert>;
}
import type { AlertSeverity as _AlertSeverity, Anomaly as _Anomaly, AnomalyType as _AnomalyType, EmergencyAlert as _EmergencyAlert, Incident as _Incident, IncidentStatus as _IncidentStatus, Route as _Route, SystemComponent as _SystemComponent, SystemStatus as _SystemStatus, TrafficLevel as _TrafficLevel, TrafficSegment as _TrafficSegment, TrafficSnapshot as _TrafficSnapshot, WeatherCondition as _WeatherCondition, WeatherData as _WeatherData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeEmergency(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeEmergency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeEmergency(arg0);
            return result;
        }
    }
    async computeOptimalRoute(arg0: string, arg1: string): Promise<Route | null> {
        if (this.processError) {
            try {
                const result = await this.actor.computeOptimalRoute(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeOptimalRoute(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnomalies(arg0: boolean): Promise<Array<Anomaly>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnomalies(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnomalies(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyAlerts(arg0: boolean): Promise<Array<EmergencyAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyAlerts(arg0);
            return result;
        }
    }
    async getIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidents();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidents();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutes();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutes();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSegments(): Promise<Array<TrafficSegment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSegments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSegments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemComponents(): Promise<Array<SystemComponent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemComponents();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemComponents();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrafficSnapshot(): Promise<TrafficSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrafficSnapshot();
                return from_candid_TrafficSnapshot_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrafficSnapshot();
            return from_candid_TrafficSnapshot_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitTimeEstimate(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitTimeEstimate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitTimeEstimate(arg0);
            return result;
        }
    }
    async getWeather(): Promise<WeatherData> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeather();
                return from_candid_WeatherData_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeather();
            return from_candid_WeatherData_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async reportIncident(arg0: string, arg1: string, arg2: string): Promise<Incident> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIncident(arg0, arg1, arg2);
                return from_candid_Incident_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIncident(arg0, arg1, arg2);
            return from_candid_Incident_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetSimulation(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSimulation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSimulation();
            return result;
        }
    }
    async resolveAnomaly(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAnomaly(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAnomaly(arg0);
            return result;
        }
    }
    async simulateTick(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateTick();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateTick();
            return result;
        }
    }
    async triggerEmergencySimulation(arg0: string, arg1: string): Promise<EmergencyAlert> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerEmergencySimulation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerEmergencySimulation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AlertSeverity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AnomalyType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnomalyType): AnomalyType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Anomaly_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Anomaly): Anomaly {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Incident_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Incident): Incident {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Route_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Route): Route {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SystemComponent_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemComponent): SystemComponent {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatus): SystemStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficLevel): TrafficLevel {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSegment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSegment): TrafficSegment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficSnapshot_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficSnapshot): TrafficSnapshot {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherCondition_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherCondition): WeatherCondition {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WeatherData_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeatherData): WeatherData {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Route]): Route | null {
    return value.length === 0 ? null : from_candid_Route_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _IncidentStatus;
    segmentId: string;
    validationScore: bigint;
    reporterNote: string;
    reportedAt: bigint;
    validatedAt: [] | [bigint];
    incidentType: string;
}): {
    id: string;
    status: IncidentStatus;
    segmentId: string;
    validationScore: bigint;
    reporterNote: string;
    reportedAt: bigint;
    validatedAt?: bigint;
    incidentType: string;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n15(_uploadFile, _downloadFile, value.status),
        segmentId: value.segmentId,
        validationScore: value.validationScore,
        reporterNote: value.reporterNote,
        reportedAt: value.reportedAt,
        validatedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.validatedAt)),
        incidentType: value.incidentType
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: number;
    lon: number;
    avgSpeed: number;
    waitTimeSeconds: bigint;
    congestionPct: bigint;
    name: string;
    district: string;
    trafficLevel: _TrafficLevel;
    vehicleCount: bigint;
}): {
    id: string;
    lat: number;
    lon: number;
    avgSpeed: number;
    waitTimeSeconds: bigint;
    congestionPct: bigint;
    name: string;
    district: string;
    trafficLevel: TrafficLevel;
    vehicleCount: bigint;
} {
    return {
        id: value.id,
        lat: value.lat,
        lon: value.lon,
        avgSpeed: value.avgSpeed,
        waitTimeSeconds: value.waitTimeSeconds,
        congestionPct: value.congestionPct,
        name: value.name,
        district: value.district,
        trafficLevel: from_candid_TrafficLevel_n22(_uploadFile, _downloadFile, value.trafficLevel),
        vehicleCount: value.vehicleCount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SystemStatus;
    uptimePct: number;
    name: string;
    lastChecked: bigint;
    failureCount: bigint;
    componentType: string;
}): {
    id: string;
    status: SystemStatus;
    uptimePct: number;
    name: string;
    lastChecked: bigint;
    failureCount: bigint;
    componentType: string;
} {
    return {
        id: value.id,
        status: from_candid_SystemStatus_n27(_uploadFile, _downloadFile, value.status),
        uptimePct: value.uptimePct,
        name: value.name,
        lastChecked: value.lastChecked,
        failureCount: value.failureCount,
        componentType: value.componentType
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fromDistrict: string;
    name: string;
    segments: Array<string>;
    reasoning: string;
    totalDistance: number;
    alternateOf: [] | [string];
    isOptimal: boolean;
    toDistrict: string;
    estimatedMinutes: bigint;
}): {
    id: string;
    fromDistrict: string;
    name: string;
    segments: Array<string>;
    reasoning: string;
    totalDistance: number;
    alternateOf?: string;
    isOptimal: boolean;
    toDistrict: string;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        fromDistrict: value.fromDistrict,
        name: value.name,
        segments: value.segments,
        reasoning: value.reasoning,
        totalDistance: value.totalDistance,
        alternateOf: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.alternateOf)),
        isOptimal: value.isOptimal,
        toDistrict: value.toDistrict,
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeEmergencies: Array<_EmergencyAlert>;
    segments: Array<_TrafficSegment>;
    activeAnomalies: Array<_Anomaly>;
    timestamp: bigint;
    weather: _WeatherData;
    systemHealth: bigint;
}): {
    activeEmergencies: Array<EmergencyAlert>;
    segments: Array<TrafficSegment>;
    activeAnomalies: Array<Anomaly>;
    timestamp: bigint;
    weather: WeatherData;
    systemHealth: bigint;
} {
    return {
        activeEmergencies: value.activeEmergencies,
        segments: from_candid_vec_n19(_uploadFile, _downloadFile, value.segments),
        activeAnomalies: from_candid_vec_n5(_uploadFile, _downloadFile, value.activeAnomalies),
        timestamp: value.timestamp,
        weather: from_candid_WeatherData_n31(_uploadFile, _downloadFile, value.weather),
        systemHealth: value.systemHealth
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: number;
    affectedDistricts: Array<string>;
    windSpeed: number;
    updatedAt: bigint;
    recommendation: string;
    visibility: bigint;
    condition: _WeatherCondition;
}): {
    temperature: number;
    affectedDistricts: Array<string>;
    windSpeed: number;
    updatedAt: bigint;
    recommendation: string;
    visibility: bigint;
    condition: WeatherCondition;
} {
    return {
        temperature: value.temperature,
        affectedDistricts: value.affectedDistricts,
        windSpeed: value.windSpeed,
        updatedAt: value.updatedAt,
        recommendation: value.recommendation,
        visibility: value.visibility,
        condition: from_candid_WeatherCondition_n33(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    segmentId: string;
    anomalyType: _AnomalyType;
    detectedAt: bigint;
    description: string;
    isActive: boolean;
    reasoning: string;
    severity: _AlertSeverity;
}): {
    id: string;
    segmentId: string;
    anomalyType: AnomalyType;
    detectedAt: bigint;
    description: string;
    isActive: boolean;
    reasoning: string;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        segmentId: value.segmentId,
        anomalyType: from_candid_AnomalyType_n8(_uploadFile, _downloadFile, value.anomalyType),
        detectedAt: value.detectedAt,
        description: value.description,
        isActive: value.isActive,
        reasoning: value.reasoning,
        severity: from_candid_AlertSeverity_n10(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): AlertSeverity {
    return "Low" in value ? AlertSeverity.Low : "High" in value ? AlertSeverity.High : "Medium" in value ? AlertSeverity.Medium : "Critical" in value ? AlertSeverity.Critical : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Rejected: null;
} | {
    Validated: null;
} | {
    Resolved: null;
} | {
    Pending: null;
}): IncidentStatus {
    return "Rejected" in value ? IncidentStatus.Rejected : "Validated" in value ? IncidentStatus.Validated : "Resolved" in value ? IncidentStatus.Resolved : "Pending" in value ? IncidentStatus.Pending : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    NoTraffic: null;
}): TrafficLevel {
    return "Low" in value ? TrafficLevel.Low : "High" in value ? TrafficLevel.High : "Medium" in value ? TrafficLevel.Medium : "NoTraffic" in value ? TrafficLevel.NoTraffic : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Operational: null;
} | {
    Maintenance: null;
} | {
    Degraded: null;
}): SystemStatus {
    return "Failed" in value ? SystemStatus.Failed : "Operational" in value ? SystemStatus.Operational : "Maintenance" in value ? SystemStatus.Maintenance : "Degraded" in value ? SystemStatus.Degraded : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fog: null;
} | {
    Storm: null;
} | {
    Rain: null;
} | {
    Snow: null;
} | {
    Clear: null;
}): WeatherCondition {
    return "Fog" in value ? WeatherCondition.Fog : "Storm" in value ? WeatherCondition.Storm : "Rain" in value ? WeatherCondition.Rain : "Snow" in value ? WeatherCondition.Snow : "Clear" in value ? WeatherCondition.Clear : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EmergencyVehicle: null;
} | {
    Pedestrian: null;
} | {
    Obstacle: null;
} | {
    Animal: null;
} | {
    Accident: null;
} | {
    VehicleBreakdown: null;
}): AnomalyType {
    return "EmergencyVehicle" in value ? AnomalyType.EmergencyVehicle : "Pedestrian" in value ? AnomalyType.Pedestrian : "Obstacle" in value ? AnomalyType.Obstacle : "Animal" in value ? AnomalyType.Animal : "Accident" in value ? AnomalyType.Accident : "VehicleBreakdown" in value ? AnomalyType.VehicleBreakdown : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Incident>): Array<Incident> {
    return value.map((x)=>from_candid_Incident_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Route>): Array<Route> {
    return value.map((x)=>from_candid_Route_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrafficSegment>): Array<TrafficSegment> {
    return value.map((x)=>from_candid_TrafficSegment_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SystemComponent>): Array<SystemComponent> {
    return value.map((x)=>from_candid_SystemComponent_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Anomaly>): Array<Anomaly> {
    return value.map((x)=>from_candid_Anomaly_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
